name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Or 'master' if that's your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required to push to the gh-pages branch

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Or your desired Node.js version

      - name: Restore or install dependencies
        run: |
          npm ci # Installs dependencies from package-lock.json (faster and more reliable)
          # Alternatively, you can use: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # This is the directory Next.js outputs static files to with `output: 'export'`
          # The branch to publish to. If you want to deploy to the `main` or `master` branch directly
          # (e.g., if your GitHub Pages is configured to serve from root), you might need to change this.
          publish_branch: gh-pages
          # You might want to remove the .nojekyll file if you're not building a Jekyll site
          # cname: your-custom-domain.com # Uncomment and replace if you use a custom domain
